name: hilt_mobile
description: Companion app for Hilt Watch.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  hilt_core:
    path: ../hilt_core
  fl_chart: ^0.65.0
  provider: ^6.0.0
  intl: ^0.18.0
  watch_connectivity: ^0.2.2
  audioplayers: ^5.0.0
  flutter_tts: ^3.7.0
  share_plus: ^12.0.1
  screenshot: ^3.0.0
  path_provider: ^2.1.5
  flutter_ftms: ^1.1.3
  permission_handler: ^11.0.0
  flutter_blue_plus: ^1.36.8
  wakelock_plus: ^1.4.0
  google_fonts: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "assets/icon/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/sounds/
